### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Yuka0410** [Yuka0410/furima-29813#10]
#URL
https://furima-29813.herokuapp.com/

Basic認証のIDとパスワード
ID  yukasan  パスワード 1989

出品者用のメールアドレスとパスワード
ログイン名 A 　　メールアドレス　aaa@miya.com  パスワード2020sep

購入者用のメールアドレスとパスワード
ログイン名 B      メールアドレス　bbb@miya.com  パスワード2020oct

購入用カードの番号・期限・セキュリティコード　
4242424242424242 | 12/24 | 123

What
提出時間が遅くなり申し訳ありません。ご確認お願いします。
来週になると思いますので、それまでオリジナルアプリの構想やアプリの追加実装をしておくべきでしょうか？
上記は選択制になるという説明を受けたのでオリジナルアプリの構想だけでも始めて良いでしょうか？

**Comment by tnk1215** [comment]
ご提出ありがとうございます！
そしてお待たせいたしました。
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

必須機能に関わる部分ではありませんが、ご提出いただきました「購入者用のメールアドレスとパスワード
」でのログインができませんでした。
最終課題説明文でも記載する内容ですので一度ご確認いただいた方がよろしいかと思います。


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
